### ISSUE TITLE
Impossible to build the XCode project

### ISSUE THREAD

**Issue by anys357** [Champ-Goblem/IntelWiFiDriver---Voodoo80211#3]
Hi,
Thank's for you work but infortunnaly i can't build the XCode project, i got a error "Build Fail"
I'm running MacOS Mojave and XCode is on the latest version

**Comment by anys357** [comment]
If you need someone to test your project, just call me. I only use my hackintosh to test things like your project and Final Cut Pro :D

**Comment by Champ-Goblem** [comment]
Its unfortunately not anywhere near ready yet, I've only made the repo public so that people can follow the development progress, ill sort out build issues at the end but for now im just trying to get everything implemented first, but ill add this to the known issues so I remember to deal with it later.

**Comment by anys357** [comment]
ok no problem: D I will watch until it is available in alpha / beta

**Comment by anys357** [comment]
oh and do you think it will work on Intel AX200 chipset ? I will close the issue after that

**Comment by Champ-Goblem** [comment]
Ill have to look through the source code and determine if ax200 falls under MVM or DVM, ill put a list up of supported cards once its done.
